### ISSUE TITLE
Stuck at Info: Initializing SNTP

### ISSUE THREAD

**Issue by kedzior-io** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#114]
I'm using the Azure IOT example as is.

It gets stuck at (even if `WiFi.begin();` is called)

```
Step 10: IMEI: DST: 1
Modem Connected to Rogers' LTE (channel--> 38) CAT-M (preferred network). TLE CAT-M OK
 > Modem On --> True
 > IoT Hub
Info: Initializing SNTP

```

**Comment by vandebuerierune** [comment]
any updates? I'm having the same issue.

**Comment by kedzior-io** [comment]
@vandebuerierune no luck.

**Comment by vandebuerierune** [comment]
I have found a fix, In the code there is a bool HasIotHub which is initially set on false, later on it would be set on true if the iothub connectionstring is correct. However this just doesn't work for some reason. The problem was fixed when I set this boolean on true by default. My code is sending data to iothub right now and it works fluently. Right now I'm doint this in the loop just to make sure that it isn't put to false by accident again.
![image](https://user-images.githubusercontent.com/43674326/121200865-5acbcf80-c874-11eb-9569-135adaa5d8ff.png)

I also disabled the shutdown function at the bottom of the loop since shutting down and restarting the module takes to much time. By disabling this it now sends data at a much faster rate.
![image](https://user-images.githubusercontent.com/43674326/121201123-936ba900-c874-11eb-9313-353002cd062c.png)

I hope this solution helps you and others aswell!

-- Rune Vandebuerie

**Comment by kedzior-io** [comment]
@vandebuerierune I haven't had time to go through it and didn't even noticed this variable but hey I fired up with what you suggested and it seems to work. 

Awesome! Thanks!

Though now I'm getting. 

`Failed DNS lookup for my-test.azure-devices.net: 202`


Did you have the same problem?

**Comment by kedzior-io** [comment]
Closing this issue since it is solved and opened a new one referencing DNS problems:
https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G/issues/120
