### ISSUE TITLE
Which type of 18650 cell do I need?

### ISSUE THREAD

**Issue by jorisvervuurt** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#115]
I'm planning on buying a few of these boards, but it's not entirely clear to me which type of 18650 cell I need to use.

If I buy the board directly from LilyGO (through AliExpress), I assume they will send the newest 20200415 revision.

Can someone please answer the following questions? Thanks!

1. What is the minimum and maximum capacity (mAh) I can use?
2. Do I need a protected or unprotected cell (am I correct that unprotected would be OK for the 20200415 revision)?
3. Do I need button cap or flat top type?

Thanks very much in advance!

**Comment by Mr-HaleYa** [comment]
... wow ... 
anyways...

1) whatever you want, bigger mAh longer it last but over 4000 mAh and the battery is fake
2) whatever you want, the board has protection IC built-in but if you want two then you can do that
3) whatever you want, if you get protected it will be a button cap, unprotected are flat tops. it is VERY hard to fit button type in battery pack tho.

I use and recommend [SAMSUNG 35E 18650 3500MAH](https://www.18650batterystore.com/collections/18650-batteries/products/samsung-35e) but good luck finding them in stock from real suppliers since most 18650s are fake

Anything from [HERE](https://www.18650batterystore.com/collections/18650-batteries) are real and I have bought hundreds from them, get a flat top unprotected
