### ISSUE TITLE
Brownout detector was triggered when trying to start the modem using batteries

### ISSUE THREAD

**Issue by amenoni** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#136]
Hi.
I'm having a Brownout detector was triggered restart when trying to start the modem using a fully charged 18650 battery (4,19v) in the 20-4-15 version.
The problem stops if I plug the USB.

do you have any idea how to solve it?

Appreciate your help

**Comment by edge7Lux** [comment]
I have got a similar problem.
I am trying to mitigate the problem via software (which is doing one operation at a time, for instance, turn off Access Point if modem is being used), the problem is that the battery cannot provide the peak current the modem needs, something like 450ma at peak.

**Comment by edge7** [comment]
I have got a similar problem.
I am trying to mitigate the problem via software (which is doing one operation at a time, for instance, turn off Access Point if the modem is being used), the problem is that the battery cannot provide the peak current the modem needs, something like 450ma at peak.
@amenoni just as a curiosity what is your sketch roughly? Are you using GSM or LTE NB-IoT/CAT?

**Comment by LilyGO** [comment]
Do you have a video? I don't have any of those problems.Something to do with batteries
