### ISSUE TITLE
Gerber files?

### ISSUE THREAD

**Issue by saade** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#172]
I need to make a board with a different size and shape, but use the same components, can we get the gerber files? Perhaps some file we can edit using EasyEDA or Eagle?

**Comment by Mr-HaleYa** [comment]
They are not going to give you those lol. I helped design the new board and we are not allowed to just give those out since they do manufacture them and sell them as part of their business. 

They do have a smaller one that is about half the length if that would work better for you

so ya if that's all you want I highly doubt it will happen so you can close this issue. 🙃 

---
my proof of designing their boards
![image](https://user-images.githubusercontent.com/42821995/181692659-3758a4a1-3b25-40a1-97ca-9fe143472f7d.png)
