### ISSUE TITLE
The product is not avaiable for EU countries

### ISSUE THREAD

**Issue by evghenix** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#187]
I can't find the product with shipping to Germany. Looks like it's unavailable for EU countries. However it's available for russian market. 

Product link: https://aliexpress.ru/item/4000542688096.html

**Comment by LilyGO** [comment]
Hello.
The platform don't show our products to your country for the time being. 
Because your country has new policies since July, the platform needs us to provide the environmental protection tax number [EPR]. 
We have submitted it and the platform is handling. It is expected to be completed in these days.

You can also buy them   [here](https://www.tindie.com/products/lilygo/lilygo-ttgo-t-sim7000g)

**Comment by evghenix** [comment]
Thanks. Is this a new version 20200415?

**Comment by LilyGO** [comment]
yes
