### ISSUE TITLE
Charging Li-Ion battery below freezing temperature

### ISSUE THREAD

**Issue by GeirFrimann** [Xinyuan-LilyGO/LilyGO-T-SIM7000G#58]
According to many articles (e.g. [https://batteryuniversity.com/learn/article/charging_at_high_and_low_temperatures](url)), charging a Li-Ion battery below freezing temperatures will permanently damage the battery and can even be dangerous (explosion).

Does the solar charging circuit disable charging below freezing temperatures, or is there any other way to disable it, e.g. if I add a temperature sensor and if temperature drops near freezing could disable charging of the battery?
Since I'm using this microcontroller together with a Li-Ion 18650 battery which are charged from a 250mA solar panel to measure the level in a diesel tank, I really want to avoid an explosion!

**Comment by Mr-HaleYa** [comment]
The literally so many different ways you could go about this that that's probably why no one has answered...

If You want to use the temperature probe something that would be super simple is a relay that is connected to the solar panel so that when the temperature on the temperature probe is below freezing it disconnects your solar panel, that would be super easy to add and super effective as long as your temperature probe isn't garbage and doesn't die. 

Your entire problem with this though is if the lithium battery dies because it's too cold and it doesn't charge for a couple days then you're just going to be out of luck until it warms up so if you're using it to measure a diesel tank you're not going to be getting any readings until it gets warm again. Your best bet would probably be to insulate it in a box and then just go with it as long as it's not getting down to extremely cold temperatures the damage caused to the battery is negligible and it should be good for quite a few years before you even notice anything.

You're not going to get an explosion in freezing temperatures all it does is create micro tears inside of the battery that degrade it to the point where it just doesn't function, it doesn't explode.
